added precommit customized

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,93 +1,94 @@
-name: 'Bandit'
-description: 'Security Lint Python code with Bandit'
-author: 'ixxeL'
+---
+name: Bandit
+description: Security Lint Python code with Bandit
+author: ixxeL
 inputs:
   format:
-    description: 'Format errors according to the chosen formatter [csv,custom,html,json,screen,txt,xml,yaml]'
+    description: Format errors according to the chosen formatter [csv,custom,html,json,screen,txt,xml,yaml]
     required: false
-    default: 'screen'
+    default: screen
   exit-zero:
-    description: 'Exit with status code "0" even if there are errors'
+    description: Exit with status code "0" even if there are errors
     required: false
     default: 'true'
   security:
-    description: 'report only issues of a given severity level or higher [all, low, medium, high]'
+    description: report only issues of a given severity level or higher [all, low, medium, high]
     required: false
-    default: 'all'
+    default: all
   confidence:
-    description: 'report only issues of a given confidence level or higher [all, low, medium, high]'
+    description: report only issues of a given confidence level or higher [all, low, medium, high]
     required: false
-    default: 'all'
+    default: all
   output-file:
-    description: 'Redirect report to a file'
+    description: Redirect report to a file
     required: false
-    default: '""'    
+    default: '""'
   working-dir:
-    description: 'directory in which to find the Dockerfile'
+    description: directory in which to find the Dockerfile
     required: false
-    default: '.'
+    default: .
 
 runs:
-  using: "composite"
+  using: composite
   steps:
-    - id: bandit
-      run: |
-        set +e
-        echo -e "${BLUE}[ STEP - SECURITY LINTING CODE ] > Code security linting with Bandit.${BLANK}"
-        echo -e "${CYAN}[ INFO ] > Bandit version.${BLANK}"
-        bandit --version
-        echo -e "${YELLOW}[ EXECUTING ] > Executing code security linting.${BLANK}"
-        if [[ ${{ inputs.exit-zero }} = true ]]
-        then
-          echo -e "${CYAN}[ INFO ] > Exit zero mode forced.${BLANK}"
-          EXIT_ZERO="--exit-zero"
-        else
-          EXIT_ZERO=""
-        fi
+  - id: bandit
+    run: |
+      set +e
+      echo -e "${BLUE}[ STEP - SECURITY LINTING CODE ] > Code security linting with Bandit.${BLANK}"
+      echo -e "${CYAN}[ INFO ] > Bandit version.${BLANK}"
+      bandit --version
+      echo -e "${YELLOW}[ EXECUTING ] > Executing code security linting.${BLANK}"
+      if [[ ${{ inputs.exit-zero }} = true ]]
+      then
+        echo -e "${CYAN}[ INFO ] > Exit zero mode forced.${BLANK}"
+        EXIT_ZERO="--exit-zero"
+      else
+        EXIT_ZERO=""
+      fi
 
-        if [[ -z "${{ inputs.output-file }}" ]]
-        then
-          echo -e "${CYAN}[ INFO ] > No output file.${BLANK}"
-          OUTPUT=""
-        else
-          echo -e "${CYAN}[ INFO ] > Output file provided --> ${{ inputs.output-file }}.${BLANK}"
-          OUTPUT="--output ${{ inputs.output-file }}"
-        fi
+      if [[ -z "${{ inputs.output-file }}" ]]
+      then
+        echo -e "${CYAN}[ INFO ] > No output file.${BLANK}"
+        OUTPUT=""
+      else
+        echo -e "${CYAN}[ INFO ] > Output file provided --> ${{ inputs.output-file }}.${BLANK}"
+        OUTPUT="--output ${{ inputs.output-file }}"
+      fi
 
-        if [[ ${{ inputs.format }} = "json" ]]
-        then
-          bandit --verbose \
-                 --recursive \
-                 --severity-level ${{ inputs.security }} \
-                 --confidence-level ${{ inputs.confidence }} \
-                 --format ${{ inputs.format }} \
-                 ${OUTPUT} \
-                 ${EXIT_ZERO} \
-                 ${{ inputs.working-dir }} | jq -C
-        else
-          bandit --verbose \
-                 --recursive \
-                 --severity-level ${{ inputs.security }} \
-                 --confidence-level ${{ inputs.confidence }} \
-                 --format ${{ inputs.format }} \
-                 ${OUTPUT} \
-                 ${EXIT_ZERO} \
-                 ${{ inputs.working-dir }}
-        fi
-        EXIT_CODE="${PIPESTATUS[0]}"
-        if [[ ${EXIT_CODE} -ne 0 ]]
-        then
-          echo -e "${RED}[ FAIL ] > Bandit scan failed.${BLANK}"
-          exit ${EXIT_CODE}
-        else
-          echo -e "${GREEN}[ SUCCESS ] > Bandit scan succeeded.${BLANK}"
-        fi
-      shell: bash
-      env:
-        RED: \033[1;31m
-        GREEN: \033[1;32m
-        YELLOW: \033[1;33m
-        BLUE: \033[1;34m
-        PURPLE: \033[1;35m
-        CYAN: \033[1;36m
-        BLANK: \033[0m
+      if [[ ${{ inputs.format }} = "json" ]]
+      then
+        bandit --verbose \
+               --recursive \
+               --severity-level ${{ inputs.security }} \
+               --confidence-level ${{ inputs.confidence }} \
+               --format ${{ inputs.format }} \
+               ${OUTPUT} \
+               ${EXIT_ZERO} \
+               ${{ inputs.working-dir }} | jq -C
+      else
+        bandit --verbose \
+               --recursive \
+               --severity-level ${{ inputs.security }} \
+               --confidence-level ${{ inputs.confidence }} \
+               --format ${{ inputs.format }} \
+               ${OUTPUT} \
+               ${EXIT_ZERO} \
+               ${{ inputs.working-dir }}
+      fi
+      EXIT_CODE="${PIPESTATUS[0]}"
+      if [[ ${EXIT_CODE} -ne 0 ]]
+      then
+        echo -e "${RED}[ FAIL ] > Bandit scan failed.${BLANK}"
+        exit ${EXIT_CODE}
+      else
+        echo -e "${GREEN}[ SUCCESS ] > Bandit scan succeeded.${BLANK}"
+      fi
+    shell: bash
+    env:
+      RED: \033[1;31m
+      GREEN: \033[1;32m
+      YELLOW: \033[1;33m
+      BLUE: \033[1;34m
+      PURPLE: \033[1;35m
+      CYAN: \033[1;36m
+      BLANK: \033[0m
